#!/usr/bin/env bash

base_url=http://www.emacswiki.org/cgi-bin/wiki/download
dir=lisp

required_libraries="
accelerate.el
autoinfo.el
babel.el
browse-kill-ring.el
browse-kill-ring+.el
color-moccur.el
color-occur.el
dired-details.el
dired-details+.el
dired+.el
dired-sort-menu.el
dired-sort-menu+.el
ediff-trees.el
eiv.el
etags-select.el
etags-table.el
finder+.el
fsdired.el
goto-chg.el
grep-edit.el
header2.el
htmlize.el
htmlr.el
iedit.el
igrep.el
igrep-next-error.el
info+.el
isearch-all.el
isearch+.el
iterator.el
lively.el
menu-bar+.el
mgrep.el
moccur-edit.el
multi-eshell.el
multi-shell.el
multi-term.el
no-word.el
oddmuse.el
oprofile-mode.el
pos-tip.el
ppindent.el
rect-mark.el
replace+.el
sequential-command-config.el
sequential-command.el
sr-speedbar.el
synonyms.el
traverselisp.el
window-number.el
xgtags-extension.el
yaoddmuse.el
"

wget http://homepage1.nifty.com/bmonkey/emacs/elisp/completing-help.el
wget http://homepage1.nifty.com/bmonkey/emacs/elisp/iman.el
wget http://homepage1.nifty.com/bmonkey/emacs/elisp/mcomplete.el

wget http://cvs.savannah.gnu.org/viewvc/*checkout*/global/global/gtags.el
wget http://web.archive.org/web/20080117124425/http://home.tiscali.de/mgidde/source/xgtags.el

wget http://launchpad.net/mediawiki-el/2.2/2.2.2/+download/mediawiki.el
wget http://download.savannah.gnu.org/releases/bm/bm-1.53.el
wget http://www.davep.org/emacs/boxquote.el
wget http://staff.science.uva.nl/~dominik/Tools/cdlatex/cdlatex.el

wget http://homepage1.nifty.com/bmonkey/emacs/elisp/cldoc.el

wget http://www.bookshelf.jp/elc/mcomplete-history.el
wget http://www.bookshelf.jp/elc/color-grep.el

wget http://staff.science.uva.nl/~dominik/Tools/constants/constants.el
wget http://centaur.maths.qmw.ac.uk/emacs/files/dired-explore.el
wget http://www-ftp.lip6.fr/pub/emacs/elisp-archive/incoming/dired-tar.el.gz

wget http://github.com/jwiegley/eshell/blob/master/esh-toggle.el

wget --no-check-certificate https://github.com/jwiegley/eshell/raw/master/esh-toggle.el

wget http://www.wonderworks.com/download/filladapt.el
wget http://www.webweavertech.com/ovidiu/emacs/find-recursive.txt

wget http://nschum.de/src/emacs/highlight-parentheses/highlight-parentheses.el
wget http://edward.oconnor.cx/elisp/hl-sexp.el

wget http://git.savannah.gnu.org/cgit/idutils.git/plain/lisp/idutils.el

wget http://jblevins.org/projects/markdown-mode/markdown-mode.el
wget http://stud4.tuwien.ac.at/~e0225855/misc/openwith.el

wget http://www.burtzlaff.de/org-fstree/org-fstree.el

wget http://staff.science.uva.nl/~dominik/Tools/outline-magic.el

wget http://mumble.net/~campbell/emacs/paredit-beta.el

wget http://git.savannah.gnu.org/cgit/stumpwm.git/tree/contrib/stumpwm-mode.el
wget http://www.northbound-train.com/emacs/whole-line-or-region.el

optional_libraries=""

if [ -d "$dir" ]; then
    typeset -i i=0
    while [ -d "${dir}_OLD$i" ]; do
        i="$i + 1"
    done
    mv "$dir" "${dir}_OLD$i"
fi

for library in $required_libraries $optional_libraries ; do
    wget -nd -P $dir ${base_url}/${library}
    # Sleep for 2 seconds so as not to overload www.emacswiki.org
    sleep 2
done

cp makefiles/lisp lisp/Makefile
