;; Automatically generated by makeEemacs
(add-to-list 'load-path (expand-file-name "~/.emacs.d/init"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/my-lisp"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/my-lisp/tree-mode"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/packages/paredit"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/haskell-mode"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/packages/icicles"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/auctex"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/ebib/src"))
(add-to-list 'load-path (expand-file-name  "~/.emacs.d/packages/git-modes"))
(add-to-list 'load-path (expand-file-name  "~/.emacs.d/packages/magit"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/yasnippet"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/imaxima"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/bbdb/lisp"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/emms/lisp"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/gnuplot"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/doremi"))
(add-to-list 'load-path (expand-file-name  "~/.emacs.d/packages/undo-tree"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/packages/emacs-calfw"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/wget"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/completion-ui"))
;; (add-to-list 'load-path
;;              (expand-file-name "~/.emacs.d/packages/org-mode/lisp"))
;; (add-to-list 'load-path
;;              (expand-file-name "~/.emacs.d/packages/org-mode/contrib/lisp"))
;;(add-to-list 'load-path
;;             (expand-file-name "~/EuLisp/EuLisp/emacs"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/packages/emacs-calfw"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/w3m"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/wanderlust/wl"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/wanderlust/elmo"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/wanderlust/utils"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/semi"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/flim"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/apel"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/bbdb"))
(add-to-list 'load-path
             (expand-file-name "~/.emacs.d/packages/w3m"))
(setq inhibit-startup-message t)  ;; Include in init-eemacs
(setq use-file-dialog nil)  ;; Include in init-eemacs
(tool-bar-mode -1)  ;; Include in init-eemacs
(scroll-bar-mode -1)  ;; Include in init-eemacs
(load "init-runtime" nil t) ;; Include in init-eemacs
