;; Automatically generated by makeEemacs
(setq inhibit-startup-message t)  ;; Include in init-eemacs
(setq use-file-dialog nil)  ;; Include in init-eemacs
(tool-bar-mode -1)  ;; Include in init-eemacs
(scroll-bar-mode -1)  ;; Include in init-eemacs
(load "init-runtime" nil t) ;; Include in init-eemacs
