#!/bin/sh

case `uname -m` in
    i686)
    EMACS="setarch i386 -R `which emacs`"
    ;;
    x86_64)
    EMACS=`which emacs`
    ;;
esac

./makeEemacs

$EMACS --batch -q \
    --load load-eemacs.el \
    --load init-emms.el \
    --execute "(dump-emacs \"~/bin/eeemacs\" \"$EMACS\")"
